{
 "title": "Thumbnail Processing Stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Thumbnail Pod RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{\n  namespace=\"default\",\n  pod=~\"thumbnail-proc.*\",\n  container!=\"POD\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thumbnail Pod CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"default\",\n    pod=~\"redis.*|thumbnail.*\",\n    container!=\"POD\"\n  }[2m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(thumbnail_jobs_created_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Jobs Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thumbnail_jobs_created_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Jobs Succeeded Per Pod",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thumbnail_jobs_succeeded_total{namespace=\"default\", pod=~\"thumbnail-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 *\nrate(thumbnail_jobs_succeeded_total[1m])\n/\n(\n  rate(thumbnail_jobs_succeeded_total[1m])\n+ rate(thumbnail_jobs_failed_total[1m])\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(thumbnail_jobs_failed_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Processing Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(thumbnail_job_processing_seconds_bucket[5m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50 Processing Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(thumbnail_job_processing_seconds_bucket[5m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Status Ready",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (pod) (\n  kube_pod_status_ready{\n    namespace=~\"(default|monitoring)\",\n    condition=\"true\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thumbnail Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(\n  kube_pod_container_status_restarts_total{\n    namespace=\"default\",\n    pod=~\"(thumbnail-proc.*|redis.*)\"\n  }[10m]\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}